### ISSUE TITLE
How To Load Fashion CLIP 2.0

### ISSUE THREAD

**Issue by shivamtundele** [patrickjohncyh/fashion-clip#15]
Hello,

For HuggingFace API,

Does below automatically loads updated Fashion CLIP 2.0 model or is there some other identifier than "patrickjohncyh/fashion-clip"?
`processor = AutoProcessor.from_pretrained("patrickjohncyh/fashion-clip")`

TIA

**Comment by vinid** [comment]
Hello!

That call automatically loads 2.0 :)

**Comment by shivamtundele** [comment]
Thanks!
