### ISSUE TITLE
provide ranges of required packages instead of hardpinning

### ISSUE THREAD

**Issue by nicoa** [patrickjohncyh/fashion-clip#19]
Hey everybody,

thanks for the work you did here!

What do you think of loosening the pinned requirements to give just lower bounds (or at least ranges). Or is there a specific reason to have all packages pinned here?

**Comment by vinid** [comment]
Hi!

I think we set specific versions for reproducibility, but yeah it's probably better to kind of loosen some of them. Do you want to send a PR with what you think we should change?

**Comment by nicoa** [comment]
Yes, will do so - thanks for the positive feedback!

**Comment by nicoa** [comment]
Hey @vinid the PR is linked here. Please let me know if any information is missing from me :)

**Comment by vinid** [comment]
Thanks so much! 

I'll hopefully review it over the weekend!

**Comment by vinid** [comment]
merged! tysm!

**Comment by nicoa** [comment]
Thanks a lot! :)
