### ISSUE TITLE
Get Fclip image embeddings directly from image file loaded in PIL or np format

### ISSUE THREAD

**Issue by Ravishukla1234** [patrickjohncyh/fashion-clip#29]
image_embeddings = fclip.encode_images(images, batch_size=32)

The above piece of code expects images to be a list of image paths.

Can you please provide some code snippet to convert the image loaded in PIL or np format into FClip Embeddings ..

**Comment by vinid** [comment]
Hello!

You should be able to do that by [editing this part](https://github.com/patrickjohncyh/fashion-clip/blob/master/fashion_clip/fashion_clip.py#L178) of the code. Shouldn't be impossible but requires some work.

Can you save your PIL images in disk?

**Comment by vinid** [comment]
You can also use the HF model directly. This allows you to basically use PIL images right away: https://github.com/patrickjohncyh/fashion-clip?tab=readme-ov-file#hf-api

**Comment by Ravishukla1234** [comment]
> Hello!
> 
> You should be able to do that by [editing this part](https://github.com/patrickjohncyh/fashion-clip/blob/master/fashion_clip/fashion_clip.py#L178) of the code. Shouldn't be impossible but requires some work.
> 
> Can you save your PIL images in disk?

Can't save the images in disk since I was deploying it in Amazon Sagemaker Endpoint which does'nt supports write operation. But instead I saw encode_images also supports url directly, that helped me build the solution. Thanks
