### ISSUE TITLE
problem with loading pretrained weights

### ISSUE THREAD

**Issue by duyc168** [patrickjohncyh/fashion-clip#3]
hello, I run the code of "fashion-clip-master/fashion_clip_api_demo.ipynb"，but `fclip = FashionCLIP('FCLIP', dataset)` met with an error:
![1675177077240](https://user-images.githubusercontent.com/74500098/215795683-8a1651a8-7112-467b-9c87-436bf836f97d.jpg)
I notice that the link of pretrained weights is provided in the code, I was wondering how to download the pretrained weights?

**Comment by patrickjohncyh** [comment]
Hi duyc168! We're releasing the pretrained weights very soon : ) Stay tuned!

**Comment by mayanand** [comment]
Looking forward to it. Also what is the license on the pre trained weights?

**Comment by vinid** [comment]
Weights are out on HuggingFace (see the main page of the repo for more details)!

**Comment by mayanand** [comment]
@vinid Thanks for info. What is the license on this project?

**Comment by vinid** [comment]
No worries! details on licensing of the model are on HuggingFace
