### ISSUE TITLE
How was the fine-tunimg done exactly

### ISSUE THREAD

**Issue by travellingsasa** [patrickjohncyh/fashion-clip#32]
Hey there,

I am wondering how you did the fine-tuning here. You do not describe it in the paper.

Did you
1. Continue training starting from a pre trained model like open clip
2. Added a classification head and froze all other layer 
3. Added a classification head and updated image and text encoders

I don't think you did 2 or 3 since you used full sentences as captions.

How did you do it?

All the best

**Comment by vinid** [comment]
Hi!!

It's contrastive fine-tuning, we use the same task CLIP was trained on. All unfrozen.

Let me know if you need more details!

**Comment by travellingsasa** [comment]
So when you say "same task CLIP was trained on" do I correctly assume you continued training without adding a classifier?

**Comment by vinid** [comment]
Yup, we keep the same contrastive pre-training objective

**Comment by travellingsasa** [comment]
Thank you for the clarification and the super quick reply :)

**Comment by vinid** [comment]
Happy to help!!
