### ISSUE TITLE
OpenAI CLIP Version Used in Performance Comparison

### ISSUE THREAD

**Issue by KosarKeshavarz** [patrickjohncyh/fashion-clip#35]
Hi,

I noticed that you compared the performance of FashionCLIP to OpenAI CLIP. Could you please clarify which version of OpenAI CLIP was used for the comparison? Specifically, was it the ViT-L/14 model?

Thank you!

**Comment by vinid** [comment]
Hi!

No should be the exact same base model, which was the ViT32 version

**Comment by KosarKeshavarz** [comment]
> Hi!
> 
> No should be the exact same base model, which was the ViT32 version

 I'm curious to know the evaluation results of CLIP ViT-L/14 on your test sets. However, I noticed that you pre selected a subset of DEEP, Kaggle, and other datasets, which are not accessible
I'm wondering if fine-tuning CLIP base models (b-32/16) can outperform pretrained larger models in your evaluations.(or there is a chance)

**Comment by vinid** [comment]
We haven't played with the large CLIP so I don't really have an answer. It could be the case that CLIP ViT-L/14 is better than smaller domain-specific models but it is hard to say.
